import { StyleSheet } from "@react-pdf/renderer";

export const documentStyles = StyleSheet.create({
  page: {
    backgroundColor: "white",
    fontFamily: "Courier",
    paddingHorizontal: "5%",
    color: "#292A2B",
  },
  header: {
    marginHorizontal: "auto",
    marginTop: "10%",
    fontSize: "40pt",
    fontWeight: 600,
  },
  sideInfo: {
    flex: "true",
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: "15pt",
    fontWeight: 400,
    marginTop: "50pt",
  },
  tableHeaderContainer: {
    backgroundColor: "#292A2B",
    color: "white",
    flexDirection: "row",
    paddingHorizontal: "30pt",
    fontWeight: 400,
    paddingVertical: "10pt",
    borderRadius: "3pt",
  },
  table: { marginTop: "30pt" },
  tableUnit: { marginRight: "60pt" },
  tableProduct: { marginRight: "210pt" },
  tablePricePerUnit: { marginRight: "80pt" },
  tableTotalPrice: { marginRight: "50pt" },
  unitBodycolumn: { width: "105pt", textAlign: "center" },
  productBodycolumn: { width: "235pt", textAlign: "left", fontWeight: 400 },
  pricePerUnitBodycolumn: {
    width: "100pt",
    textAlign: "left",
    fontWeight: 400,
  },
  totalPriceBodycolumn: { width: "40pt", textAlign: "left", fontWeight: 400 },
  tableBody: { flexDirection: "column", fontSize: "15pt", fontWeight: 100 },
  bodyRow: {
    paddingVertical: "13pt",
    flexDirection: "row",
    borderBottomStyle: "solid",
    borderBottomWidth: "1pt",
  },
  bankAccount: { marginTop: "15%", textAlign: "center" },
  total: {
    textAlign: "center",
    paddingVertical: "10pt",
    flexDirection: "row",
    justifyContent: "center",
  },
  bold: { fontWeight: 600 },
  row: { flexDirection: "row", justifyContent: "center" },
});
